### ISSUE TITLE
Why are there leading semicolons in some of your tests?

### ISSUE THREAD

**Issue by StoneCypher** [caderek/benny#24] opened 2021-02-13 17:53 UTC
Your example code says

```javascript
  b.add('Reduce two elements', () => {
    ;[1, 2].reduce((a, b) => a + b)
  }),
```

What's with the semicolon before the array?

**Comment by StoneCypher** [comment] 2021-02-13 18:02
i converted this to an arrow and removed the leading semicolon

***it got reliably 5% slower***

what is going on here please

**Comment by caderek** [comment] 2021-09-30 21:31
Semicolons before array literals are added because I use [JavaScript Standard Style](https://standardjs.com/rules.html#semicolons). It's only a stylistic choice.

Closing, because I can't reproduce it, for each execution method results are the same (within the margin of error):

Test code:

```js
const { add, complete, cycle, save, suite } = require('../src/index')

module.exports = suite(
  'Reduce implementations comparison',

  add('reduce lose', () => {
    ;[1, 2].reduce((a, b) => a + b)
  }),

  add('reduce lose short', () => [1, 2].reduce((a, b) => a + b)),

  add('reduce wrapped', () => {
    return () => {
      ;[1, 2].reduce((a, b) => a + b)
    }
  }),

  cycle(),
  complete(),
  save({ file: 'reduce' }),
  save({ file: 'reduce', format: 'chart.html' }),
)
```

Results:

```
Running "Reduce implementations comparison" suite...
Progress: 100%

  reduce lose:
    210 229 435 ops/s, ±0.86%   | slowest, 0.86% slower

  reduce lose short:
    212 057 967 ops/s, ±0.56%   | fastest

  reduce wrapped:
    211 433 807 ops/s, ±0.94%   | 0.29% slower

Finished 3 cases!
  Fastest: reduce lose short
  Slowest: reduce lose
```

**Closed by caderek** 2021-09-30 21:31 UTC

**Comment by StoneCypher** [comment] 2021-09-30 21:46
so you don't care that just removing the stylistic choice speeds this up 5%?
